# Generated by Django 4.2.15 on 2024-09-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_heartrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeartRate',
        ),
    ]
