# Generated by Django 4.2.15 on 2024-10-29 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_delete_heartrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='temperature',
            name='data',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
